# Armstrong Number

In [11]:
num = parse(Int64 , readline())
num1 = num
sum = 0
lengthOfNum = 0
while(num1 > 0)
    num1 = fld(num1 , 10)
    lengthOfNum += 1
end

num1 = num
while(num1 > 0)
    remainder = rem(num1 , 10)
    sum = sum + (remainder^lengthOfNum)
    num1 = fld(num1 , 10)
end

if(sum == num)
    print("Armstrong")
else
    print("Not Armstrong")
end


stdin> 1634
Armstrong

# Pizza Delivery App

In [12]:
print("Enter 1 for Admin Panel")
print("ENter 2 for Customer Panel")

choice = parse(Int64 , readline())

totalPizza = 15

if choice == 1
    print("Enter 1 for Login\nEnter 2 for Menu\nEnter 3 for Stock Management\nEnter 0 for logout")
    choice = parse(Int64 , readline())
    while choice != 0        
        if choice == 1
            print("Enter Name: ")
            adminName = readline()
        elseif choice == 2
            print("The menu...........")
        elseif choice == 3
            print("Enter the pizza you want to add")
            newPizza = parse(Int64 , readline())
            totalPizza += newPizza
        print("Enter 1 for Login\nEnter 2 for Menu\nEnter 3 for Stock Management\nEnter 0 for logout")
        choice = parse(Int64 , readline())
        end
    end
    
elseif choice == 2
    print("Enter 1 for Login\nEnter 2 for Menu\nEnter 3 for Stock Management\nEnter 0 for logout")
    choice = parse(Int64 , readline())
    while choice != 0        
        if choice == 1
            print("Enter Name: ")
            adminName = readline()
        elseif choice == 2
            print("The menu...........")
        elseif choice == 3
            print("Enter the pizza you want to buy")
            newPizza = parse(Int64 , readline())
            totalPizza -= newPizza
        print("Enter 1 for Login\nEnter 2 for Menu\nEnter 3 for Stock Management\nEnter 0 for logout")
        choice = parse(Int64 , readline())
        end
    end
end            

Enter 1 for Admin PanelENter 2 for Customer Panelstdin> 2
Enter 1 for Login
Enter 2 for Menu
Enter 3 for Stock Management
Enter 0 for logoutstdin> 1
Enter Name: stdin> Alpha
Enter Name: 

LoadError: InterruptException:

# Array


1-d array

In [1]:
graphics = [1 , 6 , 7]
print(typeof(graphics))

Array{Int64,1}

In [2]:
newArr = ["farman" , "julia"]
print(typeof(newArr))

Array{String,1}

Uninitialized array

In [5]:
graph = [1 , 3;9 , 3]
print(graph)

LoadError: syntax: unexpected semicolon in array expression around In[5]:1

In [4]:
print(typeof(graph))

Array{Int64,1}

Collect() and range() function for creating array

In [15]:
arr1 = collect(1 : 3 : 30)
print(arr1)

arr2 = range(1 , length = 10 ,stop =  20)
print("\n",arr2)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28]
1.0:2.111111111111111:20.0

In [18]:
for i in arr2
    print(i, "\n")
end

1.0
3.111111111111111
5.222222222222222
7.333333333333333
9.444444444444445
11.555555555555555
13.666666666666666
15.777777777777779
17.88888888888889
20.0


# Populating an array

zeros(datatype , row , column)
ones(datatype , row , column)
rand(row , column)

In [19]:
arr3 = zeros(Int64 , 5 , 3)

5×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0

In [20]:
arr3 = ones(Int64 , 5 , 3)

5×3 Array{Int64,2}:
 1  1  1
 1  1  1
 1  1  1
 1  1  1
 1  1  1

In [25]:
arr1 = [1 3;4 6]
arr2 = [9 7;6 7]
arr3 = arr1 + arr2
print(arr3)

[10 10; 10 13]

push and pop

In [26]:
arr1 = [2 , 7 , 9 , 0]
push!(arr1 , 6)

5-element Array{Int64,1}:
 2
 7
 9
 0
 6

In [27]:
pushfirst!(arr1 , 11)

6-element Array{Int64,1}:
 11
  2
  7
  9
  0
  6

In [28]:
pop!(arr1)

6

In [29]:
print(arr1)

[11, 2, 7, 9, 0]

In [30]:
popfirst!(arr1)

11

In [31]:
print(arr1)

[2, 7, 9, 0]

splice(array_name , index) -> to remove element from particular index

In [37]:
arr1 = [2 , 7 , 9 , 0]
pop!(arr1)
popfirst!(arr1)
print(arr1)
push!(arr1 , 6)
pushfirst!(arr1 , 11)
print("\n" , arr1)
splice!(arr1 , 3)
print("\n" , arr1)

[7, 9]
[11, 7, 9, 6]
[11, 7, 6]

finding square root

In [38]:
print(sqrt(64))

8.0

In [39]:
a = 64
a^0.5

8.0

cube root

In [42]:
cbrt(125)

5.0

remainder

In [43]:
rem(153 , 10)

3

greatest common divisor

In [44]:
gcd(10 , 15)

5